### ISSUE TITLE
Update BME slides with new figures & improve text

### ISSUE THREAD

**Issue by PSSF23** [neurodata/talks#34]
Improve BME talk slides: [html](https://neurodata.io/talks/BME_talk_2022.html), [code](https://github.com/neurodata/talks/blob/master/BME_talk_2022.html)

### TODO:
- [x] Correct figure ratios and positions
- [x] Update descriptions of `synergistic` algorithms
- [x] Update `streaming forest` figure with separated [plots](https://github.com/neurodata/SDTF/blob/46da65ad18b802d86d36ccfadcd8b28cdb4229f5/docs/select.ipynb)
- [x] Add `stream synergistic forest` [plots](https://github.com/nhahn7/ProgLearn_2021-2022/blob/d4e81ddc20cb1e8d1fdcb2b9f5cfdfcf4f8eaeb8/Nick-Hahn/NDD_II/Week_7/batch_vs_streaming_synf.ipynb)
- [x] Update `kernel density` plots
